### ISSUE TITLE
API issue

### ISSUE THREAD

**Issue by Telomelonia** [getlost01/cp-contest-calender#4]
Facing this issue:

![image](https://github.com/getlost01/cp-contest-calender/assets/88445101/92cc793e-6d0c-4f36-99a5-a9bf97450094)

**Comment by Telomelonia** [comment]
Never mind... it got fixed.
But I face this issue sometimes is this from client side?

**Comment by getlost01** [comment]
Actually I am using free tier vercel hosting and some time while I push new code to development branch, server cool down for few minutes. At that time server unable to process api requests.
